--------------------------------------------------------
--  File created - Wednesday-May-06-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ENROLLMENTS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."ENROLLMENTS" 
   (	"ENROLLMENT_ID" VARCHAR2(20 BYTE), 
	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"SECTION_ID" VARCHAR2(20 BYTE), 
	"ENROLLMENT_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENT_LOGS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."EVENT_LOGS" 
   (	"LOG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"PROFESSOR_ID" VARCHAR2(20 BYTE), 
	"EVENT_TYPE" VARCHAR2(50 BYTE), 
	"SNAPSHOT_PATH" VARCHAR2(255 BYTE), 
	"TIMESTAMP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROOMS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."ROOMS" 
   (	"ROOM_ID" VARCHAR2(20 BYTE), 
	"BUILDING" VARCHAR2(100 BYTE), 
	"FLOOR" NUMBER, 
	"ROOM_TYPE" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Inactive', 
	"CAMPUS" VARCHAR2(10 BYTE) DEFAULT 'SB'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCHEDULES
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."SCHEDULES" 
   (	"SCHEDULE_ID" VARCHAR2(20 BYTE), 
	"SUBJECT_CODE" VARCHAR2(20 BYTE), 
	"SECTION_ID" VARCHAR2(20 BYTE), 
	"PROFESSOR_ID" VARCHAR2(20 BYTE), 
	"ROOM_ID" VARCHAR2(20 BYTE), 
	"TIME_START" VARCHAR2(20 BYTE), 
	"TIME_END" VARCHAR2(20 BYTE), 
	"CLASS_DAYS" VARCHAR2(50 BYTE), 
	"SUBJECT_TYPE" VARCHAR2(10 BYTE) DEFAULT 'Lec'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SECTIONS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."SECTIONS" 
   (	"SECTION_ID" VARCHAR2(20 BYTE), 
	"CAMPUS" VARCHAR2(10 BYTE), 
	"COURSE" VARCHAR2(20 BYTE), 
	"YEAR_LEVEL" NUMBER, 
	"SECTION_LETTER" VARCHAR2(5 BYTE), 
	"SECTION_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."STUDENTS" 
   (	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"MIDDLE_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"FACE_REFERENCE_PATH" VARCHAR2(255 BYTE), 
	"ENROLLMENT_STATUS" VARCHAR2(50 BYTE) DEFAULT 'Regular', 
	"CONTACT_NUMBER" VARCHAR2(20 BYTE), 
	"BIRTHDAY" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBJECTS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."SUBJECTS" 
   (	"SUBJECT_CODE" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"PREREQUISITES" VARCHAR2(100 BYTE), 
	"UNITS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"MIDDLE_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"CONTACT_NUMBER" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Active', 
	"FACE_REFERENCE_PATH" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CAMPUS_ADMIN.ENROLLMENTS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.ENROLLMENTS (ENROLLMENT_ID,STUDENT_ID,SECTION_ID,ENROLLMENT_DATE) values ('ENR-458725F8','24-1487','SEC-001',to_date('06-MAY-26','DD-MON-RR'));
Insert into CAMPUS_ADMIN.ENROLLMENTS (ENROLLMENT_ID,STUDENT_ID,SECTION_ID,ENROLLMENT_DATE) values ('ENR-73575988','26-0001','SEC-001',to_date('06-MAY-26','DD-MON-RR'));
Insert into CAMPUS_ADMIN.ENROLLMENTS (ENROLLMENT_ID,STUDENT_ID,SECTION_ID,ENROLLMENT_DATE) values ('ENR-F754B631','26-0002','SEC-001',to_date('06-MAY-26','DD-MON-RR'));
Insert into CAMPUS_ADMIN.ENROLLMENTS (ENROLLMENT_ID,STUDENT_ID,SECTION_ID,ENROLLMENT_DATE) values ('ENR-0AA78A8B','24-1507','SEC-001',to_date('06-MAY-26','DD-MON-RR'));
Insert into CAMPUS_ADMIN.ENROLLMENTS (ENROLLMENT_ID,STUDENT_ID,SECTION_ID,ENROLLMENT_DATE) values ('ENR-6459DD65','26-0003','SEC-001',to_date('06-MAY-26','DD-MON-RR'));
Insert into CAMPUS_ADMIN.ENROLLMENTS (ENROLLMENT_ID,STUDENT_ID,SECTION_ID,ENROLLMENT_DATE) values ('ENR-B771ECF0','24-1682','SEC-001',to_date('06-MAY-26','DD-MON-RR'));
REM INSERTING into CAMPUS_ADMIN.EVENT_LOGS
SET DEFINE OFF;
REM INSERTING into CAMPUS_ADMIN.ROOMS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.ROOMS (ROOM_ID,BUILDING,FLOOR,ROOM_TYPE,STATUS,CAMPUS) values ('IL602','New Academic Building',6,'Lecture Room','Inactive','SB');
Insert into CAMPUS_ADMIN.ROOMS (ROOM_ID,BUILDING,FLOOR,ROOM_TYPE,STATUS,CAMPUS) values ('IL703','New Academic Building',7,'Lecture Room','Inactive','SB');
Insert into CAMPUS_ADMIN.ROOMS (ROOM_ID,BUILDING,FLOOR,ROOM_TYPE,STATUS,CAMPUS) values ('IK504','Bautista Building',7,'Computer Laboratory','Inactive','SB');
Insert into CAMPUS_ADMIN.ROOMS (ROOM_ID,BUILDING,FLOOR,ROOM_TYPE,STATUS,CAMPUS) values ('IK604','Bautista Building',6,'Computer Laboratory','Inactive','SB');
REM INSERTING into CAMPUS_ADMIN.SCHEDULES
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.SCHEDULES (SCHEDULE_ID,SUBJECT_CODE,SECTION_ID,PROFESSOR_ID,ROOM_ID,TIME_START,TIME_END,CLASS_DAYS,SUBJECT_TYPE) values ('SCH-2144','SE101','SEC-001','PRO-0001','IK604','02:30 PM','05:30 PM','Thursday/Thu','Lec');
Insert into CAMPUS_ADMIN.SCHEDULES (SCHEDULE_ID,SUBJECT_CODE,SECTION_ID,PROFESSOR_ID,ROOM_ID,TIME_START,TIME_END,CLASS_DAYS,SUBJECT_TYPE) values ('SCH-5651','IPT101','SEC-001','PRO-0001','IL703','07:00 AM','09:00 AM','Thursday/Thu','Lec');
REM INSERTING into CAMPUS_ADMIN.SECTIONS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.SECTIONS (SECTION_ID,CAMPUS,COURSE,YEAR_LEVEL,SECTION_LETTER,SECTION_NAME) values ('SEC-001','SB','IT',2,'A','SBIT2A');
Insert into CAMPUS_ADMIN.SECTIONS (SECTION_ID,CAMPUS,COURSE,YEAR_LEVEL,SECTION_LETTER,SECTION_NAME) values ('SEC-002','SB','IT',2,'B','SBIT2B');
REM INSERTING into CAMPUS_ADMIN.STUDENTS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS,CONTACT_NUMBER,BIRTHDAY,ADDRESS) values ('24-1507','Edrian','Cortes','Rodriguez','rodriguez_24-1507_face.jpg','Regular',null,null,null);
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS,CONTACT_NUMBER,BIRTHDAY,ADDRESS) values ('23-2244','Darrel Christian David','Asinas','Datoon','datoon_23-2244_face.jpg','Dropped','0995 345 2132','2004-02-08','01 Nawasa Line Cor. Sampaguita Ave., Brgy. Pasong Tamo, Quezon City 1107');
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS,CONTACT_NUMBER,BIRTHDAY,ADDRESS) values ('24-1487','Daniel','Reta','Pelicano','pelicano_24-1487_face.jpg','Regular','0985 746 3843','2007-04-04','01 Mangahan St. Cor. Hotdog Road, Brgy. Pasong Daga, Quezon City 1132');
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS,CONTACT_NUMBER,BIRTHDAY,ADDRESS) values ('24-1506','James','Patrick','Jason','jason_24-1506_face.jpg','Regular',null,null,null);
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS,CONTACT_NUMBER,BIRTHDAY,ADDRESS) values ('26-0001','Edrian','Cortes','Rodrigo','rodrigo_26-0001_face.jpg','Regular',null,null,null);
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS,CONTACT_NUMBER,BIRTHDAY,ADDRESS) values ('26-0002','Edrian','Patrick','Rodriguez','rodriguez_26-0002_face.jpg','Regular','0991 455 7132','2005-12-20','123 Mapayapa Village 3, Brgy. Pasong Bato, Quezon City 1240');
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS,CONTACT_NUMBER,BIRTHDAY,ADDRESS) values ('26-0003','Stephanny','Curimao','Santos','santos_26-0003_face.jpg','Regular','0994 235 8743','2005-02-17','Sauyo St., Brgy. Sauyo, Quezon City 1293');
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS,CONTACT_NUMBER,BIRTHDAY,ADDRESS) values ('24-1682','Rohan','Ungria','Taylor','taylor_24-1682_face.jpg','Regular','0967 388 2070','2006-09-16','34 Republic Ave. Fairview, Quezon City');
REM INSERTING into CAMPUS_ADMIN.SUBJECTS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('IM101','Advance Database Systems','CC105, PF101, IS104',3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('IPT101','Integrative Programming and Technologies 1','PT101, PF101',3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('SE101','Software Engineering','CC105, PF101, IS104',3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('HCI101','Introduction to Human Computer Interaction',null,3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('IT301','Advanced Database Systems','IT201',3);
REM INSERTING into CAMPUS_ADMIN.USERS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.USERS (USER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PASSWORD,ROLE,EMAIL,CONTACT_NUMBER,ADDRESS,STATUS,FACE_REFERENCE_PATH) values ('PRO-0001','Joel','Malakas','Olayon','password123','Faculty',null,'0991 455 7132','01 Mangahan St. Cor. Hotdog Road, Brgy. Pasong Daga, Quezon City 1132','Active','olayon_PRO-0001_staff_face.jpg');
Insert into CAMPUS_ADMIN.USERS (USER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PASSWORD,ROLE,EMAIL,CONTACT_NUMBER,ADDRESS,STATUS,FACE_REFERENCE_PATH) values ('ADMIN-0001','Theresita','Victorious','Atienza','password123','Principal',null,null,null,'Active',null);
Insert into CAMPUS_ADMIN.USERS (USER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PASSWORD,ROLE,EMAIL,CONTACT_NUMBER,ADDRESS,STATUS,FACE_REFERENCE_PATH) values ('HR-0001','Osward','Pogi','Puriran','$2a$11$91lEYO/ASajG4tjXiiLb5ezuHFB1GdrQdm78oW0chDxiW6nXHS69O','Registrar',null,null,null,'Active',null);
Insert into CAMPUS_ADMIN.USERS (USER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PASSWORD,ROLE,EMAIL,CONTACT_NUMBER,ADDRESS,STATUS,FACE_REFERENCE_PATH) values ('GRD-0001','Bryan Malachi','Hotdog','Nayan','password123','Guard',null,null,null,'Active',null);
--------------------------------------------------------
--  Constraints for Table EVENT_LOGS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."EVENT_LOGS" MODIFY ("LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."EVENT_LOGS" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."EVENT_LOGS" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROOMS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."ROOMS" ADD PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."STUDENTS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."STUDENTS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."STUDENTS" ADD PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SECTIONS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."SECTIONS" ADD PRIMARY KEY ("SECTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CAMPUS_ADMIN"."SECTIONS" ADD UNIQUE ("SECTION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENROLLMENTS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."ENROLLMENTS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."ENROLLMENTS" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."ENROLLMENTS" ADD PRIMARY KEY ("ENROLLMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCHEDULES
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" MODIFY ("SUBJECT_CODE" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD PRIMARY KEY ("SCHEDULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBJECTS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."SUBJECTS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SUBJECTS" MODIFY ("UNITS" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SUBJECTS" ADD PRIMARY KEY ("SUBJECT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENROLLMENTS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."ENROLLMENTS" ADD CONSTRAINT "FK_ENR_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "CAMPUS_ADMIN"."STUDENTS" ("STUDENT_ID") ENABLE;
  ALTER TABLE "CAMPUS_ADMIN"."ENROLLMENTS" ADD CONSTRAINT "FK_ENR_SECTION" FOREIGN KEY ("SECTION_ID")
	  REFERENCES "CAMPUS_ADMIN"."SECTIONS" ("SECTION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT_LOGS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."EVENT_LOGS" ADD CONSTRAINT "FK_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "CAMPUS_ADMIN"."STUDENTS" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEDULES
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD CONSTRAINT "FK_SCHED_SUBJECT" FOREIGN KEY ("SUBJECT_CODE")
	  REFERENCES "CAMPUS_ADMIN"."SUBJECTS" ("SUBJECT_CODE") ENABLE;
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD CONSTRAINT "FK_SCHED_SECTION" FOREIGN KEY ("SECTION_ID")
	  REFERENCES "CAMPUS_ADMIN"."SECTIONS" ("SECTION_ID") ENABLE;
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD CONSTRAINT "FK_SCHED_PROF" FOREIGN KEY ("PROFESSOR_ID")
	  REFERENCES "CAMPUS_ADMIN"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD CONSTRAINT "FK_SCHED_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "CAMPUS_ADMIN"."ROOMS" ("ROOM_ID") ENABLE;
