--------------------------------------------------------
--  File created - Tuesday-April-28-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ENROLLMENTS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."ENROLLMENTS" 
   (	"ENROLLMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SCHEDULE_ID" VARCHAR2(20 BYTE), 
	"STUDENT_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENT_LOGS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."EVENT_LOGS" 
   (	"LOG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"PROFESSOR_ID" VARCHAR2(20 BYTE), 
	"EVENT_TYPE" VARCHAR2(50 BYTE), 
	"SNAPSHOT_PATH" VARCHAR2(255 BYTE), 
	"TIMESTAMP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROOMS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."ROOMS" 
   (	"ROOM_ID" VARCHAR2(20 BYTE), 
	"BUILDING" VARCHAR2(100 BYTE), 
	"FLOOR" NUMBER, 
	"ROOM_TYPE" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Inactive', 
	"CAMPUS" VARCHAR2(10 BYTE) DEFAULT 'SB'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCHEDULES
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."SCHEDULES" 
   (	"SCHEDULE_ID" VARCHAR2(20 BYTE), 
	"SUBJECT_CODE" VARCHAR2(20 BYTE), 
	"SECTION_ID" VARCHAR2(20 BYTE), 
	"PROFESSOR_ID" VARCHAR2(20 BYTE), 
	"ROOM_ID" VARCHAR2(20 BYTE), 
	"TIME_START" VARCHAR2(20 BYTE), 
	"TIME_END" VARCHAR2(20 BYTE), 
	"CLASS_DAYS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SECTIONS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."SECTIONS" 
   (	"SECTION_ID" VARCHAR2(20 BYTE), 
	"CAMPUS" VARCHAR2(10 BYTE), 
	"COURSE" VARCHAR2(20 BYTE), 
	"YEAR_LEVEL" NUMBER, 
	"SECTION_LETTER" VARCHAR2(5 BYTE), 
	"SECTION_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."STUDENTS" 
   (	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"MIDDLE_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"FACE_REFERENCE_PATH" VARCHAR2(255 BYTE), 
	"ENROLLMENT_STATUS" VARCHAR2(50 BYTE) DEFAULT 'Regular'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBJECTS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."SUBJECTS" 
   (	"SUBJECT_CODE" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"PREREQUISITES" VARCHAR2(100 BYTE), 
	"UNITS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"MIDDLE_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"ROLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CAMPUS_ADMIN.ENROLLMENTS
SET DEFINE OFF;
REM INSERTING into CAMPUS_ADMIN.EVENT_LOGS
SET DEFINE OFF;
REM INSERTING into CAMPUS_ADMIN.ROOMS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.ROOMS (ROOM_ID,BUILDING,FLOOR,ROOM_TYPE,STATUS,CAMPUS) values ('IL-602','New Academic Building',6,'Lecture Room','Inactive','SB');
Insert into CAMPUS_ADMIN.ROOMS (ROOM_ID,BUILDING,FLOOR,ROOM_TYPE,STATUS,CAMPUS) values ('IL-703','New Academic Building',7,'Lecture Room','Inactive','SB');
Insert into CAMPUS_ADMIN.ROOMS (ROOM_ID,BUILDING,FLOOR,ROOM_TYPE,STATUS,CAMPUS) values ('IK-504','Bautista Building',7,'Computer Laboratory','Inactive','SB');
Insert into CAMPUS_ADMIN.ROOMS (ROOM_ID,BUILDING,FLOOR,ROOM_TYPE,STATUS,CAMPUS) values ('IK-604','Bautista Building',6,'Computer Laboratory','Inactive','SB');
REM INSERTING into CAMPUS_ADMIN.SCHEDULES
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.SCHEDULES (SCHEDULE_ID,SUBJECT_CODE,SECTION_ID,PROFESSOR_ID,ROOM_ID,TIME_START,TIME_END,CLASS_DAYS) values ('SCH-2144','SE101','SEC-001','PRO-0001','IK-604','14:30','17:30','Thursday');
Insert into CAMPUS_ADMIN.SCHEDULES (SCHEDULE_ID,SUBJECT_CODE,SECTION_ID,PROFESSOR_ID,ROOM_ID,TIME_START,TIME_END,CLASS_DAYS) values ('SCH-5651','IPT101','SEC-001','PRO-0001','IK-604','10:30','13:30','Thursday');
REM INSERTING into CAMPUS_ADMIN.SECTIONS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.SECTIONS (SECTION_ID,CAMPUS,COURSE,YEAR_LEVEL,SECTION_LETTER,SECTION_NAME) values ('SEC-001','SB','IT',2,'A','SBIT2A');
Insert into CAMPUS_ADMIN.SECTIONS (SECTION_ID,CAMPUS,COURSE,YEAR_LEVEL,SECTION_LETTER,SECTION_NAME) values ('SEC-002','SB','IT',2,'B','SBIT2B');
REM INSERTING into CAMPUS_ADMIN.STUDENTS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS) values ('24-1507','Edrian','Cortes','Rodriguez','rodriguez_24-1507_face.jpg','Regular');
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS) values ('23-2244','Darrel Christian David','Asinas','Datoon','datoon_23-2244_face.jpg','Regular');
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS) values ('24-1487','Daniel','Reta','Pelicano','pelicano_24-1487_face.jpg','Regular');
Insert into CAMPUS_ADMIN.STUDENTS (STUDENT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,FACE_REFERENCE_PATH,ENROLLMENT_STATUS) values ('24-1506','James','Patrick','Jason','jason_24-1506_face.jpg','Regular');
REM INSERTING into CAMPUS_ADMIN.SUBJECTS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('IM101','Advance Database Systems','CC105, PF101, IS104',3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('IPT101','Integrative Programming and Technologies 1','PT101, PF101',3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('SE101','Software Engineering','CC105, PF101, IS104',3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('HCI101','Introduction to Human Computer Interaction',null,3);
REM INSERTING into CAMPUS_ADMIN.USERS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.USERS (USER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PASSWORD,ROLE) values ('PRO-0001','Joel','Malakas','Olayon','$2a$11$133L3OF9MW5QelxKtNc3KuDuj8ZSvK5mXuks/TmsLtx7GPqC.lQg.','Faculty');
Insert into CAMPUS_ADMIN.USERS (USER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PASSWORD,ROLE) values ('PRO-0002','Benjamin','Diligent','Molinar','$2a$11$Zjj8Q7RbJllfVrWS4ZmElOk9tqCjTSq5vXj96YFqLfPrNXy84odLi','Faculty');
Insert into CAMPUS_ADMIN.USERS (USER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PASSWORD,ROLE) values ('ADMIN-0001','Theresita','Victorious','Atienza','$2a$11$I4rddzGM0OauiWRBRUKa5uCVmShOKSBPLoRp5WIdx160Z0/flSPt.','Principal');
Insert into CAMPUS_ADMIN.USERS (USER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PASSWORD,ROLE) values ('HR-0001','Osward','Pogi','Puriran','$2a$11$a/WGtQMjr9Eo/Mhaa3gX/O9a/kU/JmDoGWrdFnbeP16rfWWfvkGf6','Registrar');
Insert into CAMPUS_ADMIN.USERS (USER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PASSWORD,ROLE) values ('GRD-0001','Bryan Malachi','Hotdog','Nayan','$2a$11$Ospbb0Y0dTloFGIEK/G4BumoLAej6Gg6qpTGxr7IQ2lxBn9wYOh9i','Guard');
--------------------------------------------------------
--  Constraints for Table EVENT_LOGS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."EVENT_LOGS" MODIFY ("LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."EVENT_LOGS" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."EVENT_LOGS" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROOMS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."ROOMS" ADD PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."STUDENTS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."STUDENTS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."STUDENTS" ADD PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SECTIONS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."SECTIONS" ADD PRIMARY KEY ("SECTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CAMPUS_ADMIN"."SECTIONS" ADD UNIQUE ("SECTION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENROLLMENTS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."ENROLLMENTS" MODIFY ("ENROLLMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."ENROLLMENTS" ADD PRIMARY KEY ("ENROLLMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCHEDULES
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" MODIFY ("SUBJECT_CODE" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD PRIMARY KEY ("SCHEDULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBJECTS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."SUBJECTS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SUBJECTS" MODIFY ("UNITS" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SUBJECTS" ADD PRIMARY KEY ("SUBJECT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENROLLMENTS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."ENROLLMENTS" ADD CONSTRAINT "FK_ENROLL_SCHED" FOREIGN KEY ("SCHEDULE_ID")
	  REFERENCES "CAMPUS_ADMIN"."SCHEDULES" ("SCHEDULE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT_LOGS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."EVENT_LOGS" ADD CONSTRAINT "FK_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "CAMPUS_ADMIN"."STUDENTS" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEDULES
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD CONSTRAINT "FK_SCHED_SUBJECT" FOREIGN KEY ("SUBJECT_CODE")
	  REFERENCES "CAMPUS_ADMIN"."SUBJECTS" ("SUBJECT_CODE") ENABLE;
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD CONSTRAINT "FK_SCHED_SECTION" FOREIGN KEY ("SECTION_ID")
	  REFERENCES "CAMPUS_ADMIN"."SECTIONS" ("SECTION_ID") ENABLE;
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD CONSTRAINT "FK_SCHED_PROF" FOREIGN KEY ("PROFESSOR_ID")
	  REFERENCES "CAMPUS_ADMIN"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "CAMPUS_ADMIN"."SCHEDULES" ADD CONSTRAINT "FK_SCHED_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "CAMPUS_ADMIN"."ROOMS" ("ROOM_ID") ENABLE;
