--------------------------------------------------------
--  File created - Wednesday-May-06-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBJECTS
--------------------------------------------------------

  CREATE TABLE "CAMPUS_ADMIN"."SUBJECTS" 
   (	"SUBJECT_CODE" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"PREREQUISITES" VARCHAR2(100 BYTE), 
	"UNITS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CAMPUS_ADMIN.SUBJECTS
SET DEFINE OFF;
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('IM101','Advance Database Systems','CC105, PF101, IS104',3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('IPT101','Integrative Programming and Technologies 1','PT101, PF101',3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('SE101','Software Engineering','CC105, PF101, IS104',3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('HCI101','Introduction to Human Computer Interaction',null,3);
Insert into CAMPUS_ADMIN.SUBJECTS (SUBJECT_CODE,TITLE,PREREQUISITES,UNITS) values ('IT301','Advanced Database Systems','IT201',3);
--------------------------------------------------------
--  DDL for Index SYS_C008247
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMPUS_ADMIN"."SYS_C008247" ON "CAMPUS_ADMIN"."SUBJECTS" ("SUBJECT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SUBJECTS
--------------------------------------------------------

  ALTER TABLE "CAMPUS_ADMIN"."SUBJECTS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SUBJECTS" MODIFY ("UNITS" NOT NULL ENABLE);
  ALTER TABLE "CAMPUS_ADMIN"."SUBJECTS" ADD PRIMARY KEY ("SUBJECT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
