# File: scripts/make_linux_compatible.py
# Version: v1.2
# Changes: Fixed comprehensive || to CONCAT conversion, handles complex SQL patterns and CASE statements

import os
import re
import glob
import json

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def convert_database_schema():
    print("[SYSTEM] Converting Oracle Schema to MariaDB...")
    input_file = os.path.join(BASE_DIR, "database", "schema.sql")
    output_file = os.path.join(BASE_DIR, "database", "schema_mariadb.sql")
    
    if not os.path.exists(input_file):
        print("[WARNING] schema.sql not found. Skipping DB conversion.")
        return

    with open(input_file, 'r', encoding='utf-8') as f:
        sql = f.read()

    # Structural Cleanup
    sql = re.sub(r'DROP .*? cascade constraints;', '', sql, flags=re.IGNORECASE)
    sql = re.sub(r'SET DEFINE OFF;', '', sql)
    sql = sql.replace('"CAMPUS_ADMIN".', '').replace('"', '')
    sql = re.sub(r'VARCHAR2\(([0-9]+)\s+BYTE\)', r'VARCHAR(\1)', sql)
    
    # FIX: Robust NUMBER mapping for exact precision
    sql = re.sub(r'NUMBER\(([0-9]+),\s*([0-9]+)\)', r'DECIMAL(\1,\2)', sql)
    sql = re.sub(r'NUMBER GENERATED BY DEFAULT AS IDENTITY.*?,', 'INT AUTO_INCREMENT,', sql, flags=re.DOTALL)
    sql = re.sub(r'\bNUMBER\b', 'INT', sql)
    
    sql = re.sub(r'DATE DEFAULT TRUNC\(SYSDATE\)', 'DATE DEFAULT (CURRENT_DATE)', sql)
    sql = re.sub(r'DATE DEFAULT SYSDATE', 'DATETIME DEFAULT CURRENT_TIMESTAMP', sql)
    sql = re.sub(r'TIMESTAMP \(6\) DEFAULT CURRENT_TIMESTAMP', 'DATETIME DEFAULT CURRENT_TIMESTAMP', sql)
    
    # FIX: Remove Sequence creation completely (MariaDB uses Auto-Increment / Subqueries)
    sql = re.sub(r'CREATE SEQUENCE.*?GLOBAL\s*;', '', sql, flags=re.DOTALL)
    sql = re.sub(r'/\n\s*CREATE TRIGGER.*?/\n', '', sql, flags=re.DOTALL)
    sql = re.sub(r'CREATE OR REPLACE EDITIONABLE TRIGGER.*?ALTER TRIGGER.*?ENABLE;', '', sql, flags=re.DOTALL)
    
    # FIX: MariaDB triggers without NEXTVAL
    mariadb_triggers = """
DELIMITER //

CREATE TRIGGER TRG_SECTIONS_AUTO_ID BEFORE INSERT ON SECTIONS FOR EACH ROW
BEGIN 
    IF NEW.SECTION_ID IS NULL OR NEW.SECTION_ID = '' THEN 
        SET NEW.SECTION_ID = CONCAT('SEC-', LPAD(
            (SELECT COALESCE(MAX(CAST(SUBSTRING(SECTION_ID, 5) AS UNSIGNED)), 0) + 1 FROM SECTIONS), 
        3, '0')); 
    END IF; 
END; //

CREATE TRIGGER TRG_UPDATE_ENROLLMENT_STATUS BEFORE UPDATE ON ENROLLMENTS FOR EACH ROW
BEGIN 
    IF NEW.CONSECUTIVE_ABSENCES >= 3 AND NEW.ENROLLMENT_STATUS = 'Enrolled' THEN 
        SET NEW.ENROLLMENT_STATUS = 'Unofficially Dropped'; 
    END IF; 
    IF NEW.CONSECUTIVE_ABSENCES = 0 AND OLD.ENROLLMENT_STATUS = 'Unofficially Dropped' THEN 
        SET NEW.ENROLLMENT_STATUS = 'Enrolled'; 
    END IF; 
END; //

DELIMITER ;
"""
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(sql + mariadb_triggers)

def mutate_csharp_backend():
    print("[SYSTEM] Mutating C# Backend for MySQL compatibility...")
    
    # 1. Update .csproj (FIX: Added re.DOTALL)
    csproj_path = os.path.join(BASE_DIR, "campus-backend", "campus-backend.csproj")
    with open(csproj_path, 'r', encoding='utf-8') as f: csproj = f.read()
    csproj = re.sub(r'<PackageReference Include="Oracle\.ManagedDataAccess\.Core".*?/>', '<PackageReference Include="MySqlConnector" Version="2.3.5" />', csproj, flags=re.DOTALL)
    with open(csproj_path, 'w', encoding='utf-8') as f: f.write(csproj)

    # 2. Update appsettings.json (FIX: Native JSON Parsing prevents fallback chain violations)
    appsettings_path = os.path.join(BASE_DIR, "campus-backend", "appsettings.json")
    with open(appsettings_path, 'r', encoding='utf-8') as f: settings = json.load(f)
    if "OracleConnection" in settings.get("ConnectionStrings", {}):
        del settings["ConnectionStrings"]["OracleConnection"]
    settings.setdefault("ConnectionStrings", {})["DefaultConnection"] = "Server=localhost;Database=campus_admin;User=root;Password=admin;"
    with open(appsettings_path, 'w', encoding='utf-8') as f: json.dump(settings, f, indent=2)

    # 3. Mutate Repositories
    repo_files = glob.glob(os.path.join(BASE_DIR, "campus-backend", "Repositories", "*.cs"))
    for file_path in repo_files:
        with open(file_path, 'r', encoding='utf-8') as f: code = f.read()
        
        # FIX: Import statement conversion (Oracle -> MySQL)
        code = code.replace("using Oracle.ManagedDataAccess.Client;", "using MySqlConnector;")
        code = code.replace("OracleConnection", "MySqlConnection")
        code = code.replace("OracleCommand", "MySqlCommand")
        code = code.replace("OracleDataReader", "MySqlDataReader")
        
        # FIX: Comment out BindByName (doesn't exist in MySqlConnector)
        code = re.sub(r'([a-zA-Z0-9_]+\.BindByName\s*=\s*true;)', r'// \1  // MYSQL: BindByName not supported', code)
        
        # FIX: Convert Oracle || string concatenation to MySQL CONCAT()
        # Pattern 1: Simple LIKE pattern - 'string' || :param || 'string'
        code = re.sub(r"'%'\s*\|\|\s*:([a-zA-Z0-9_]+)\s*\|\|\s*'%'", r"CONCAT('%', @\1, '%')", code)
        
        # Pattern 2: Professor name concatenation with CASE
        # "u.First_Name || CASE WHEN u.MIDDLE_NAME IS NOT NULL THEN ' ' || u.MIDDLE_NAME ELSE '' END || ' ' || u.Last_Name AS Professor_Name"
        code = code.replace(
            "u.First_Name || CASE WHEN u.MIDDLE_NAME IS NOT NULL THEN ' ' || u.MIDDLE_NAME ELSE '' END || ' ' || u.Last_Name AS Professor_Name",
            "CONCAT(u.First_Name, CASE WHEN u.MIDDLE_NAME IS NOT NULL THEN CONCAT(' ', u.MIDDLE_NAME) ELSE '' END, ' ', u.Last_Name) AS Professor_Name"
        )
        
        # Pattern 3: Generic line-by-line || replacement for any remaining concatenations
        # Process line-by-line to avoid breaking other operators
        lines = code.split('\n')
        for i, line in enumerate(lines):
            # Only process lines that contain both || and SQL indicators
            if ' || ' in line and ('SELECT' in line or 'FROM' in line or '@"' in line or 'CASE' in line):
                # Skip lines that are already CONCAT or in C# code (not SQL)
                if 'CONCAT' not in line and '//' not in line.split('||')[0]:
                    # Pattern: expr || 'string' || expr
                    # Replace sequence of || with CONCAT wrapper
                    # This is a multi-step process to handle nested structures
                    
                    # Step 1: Find the portion with || operators
                    if '@"' in line:  # SQL string literal
                        # Extract SQL string portion
                        match = re.search(r'@"(.*?)"', line, re.DOTALL)
                        if match and ' || ' in match.group(1):
                            sql_part = match.group(1)
                            # Replace || with placeholder to avoid breaking CASE expressions
                            # Count the || operators
                            concat_count = sql_part.count(' || ')
                            if concat_count > 0:
                                # Simple approach: wrap entire concatenated expression in CONCAT
                                # Split by || and rejoin with CONCAT syntax
                                parts = [p.strip() for p in sql_part.split(' || ')]
                                if len(parts) > 1:
                                    converted = f"CONCAT({', '.join(parts)})"
                                    line = line.replace(f'@"{sql_part}"', f'@"{converted}"')
                    
                    lines[i] = line
        
        code = '\n'.join(lines)
        
        # FIX: Parameter syntax conversion (Oracle :param -> MySQL @param)
        # Do this LAST to avoid double-conversion
        code = re.sub(r':([a-zA-Z0-9_]+)', r'@\1', code)
        
        with open(file_path, 'w', encoding='utf-8') as f: f.write(code)

if __name__ == "__main__":
    convert_database_schema()
    mutate_csharp_backend()
    print("[SUCCESS] System is now natively configured for Linux/Raspberry Pi.")